/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'livelazily' at '16-4-27 下午7:35' with Gradle 2.13
 *
 * @author livelazily, @date 16-4-27 下午7:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
